name: modul3
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  cupertino_icons: ^1.0.2
  video_player: ^2.2.6
  webview_flutter: ^2.0.15
  flutter_inappwebview: ^5.3.2
  chewie: ^1.2.0
  http: ^0.13.3
  get: ^4.6.6
  firebase_core: ^2.22.0
  firebase_auth: ^4.2.0
  firebase_messaging: ^14.7.5
  sms_autofill: ^2.3.0
  appwrite: ^11.0.1
  shared_preferences: ^2.2.2
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/app/images/
