// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYWgoZF-wc6PutXKC1y702Zf9_8x0jl-E',
    appId: '1:649578057922:web:90238f6189d350cdc32b5b',
    messagingSenderId: '649578057922',
    projectId: 'auth-flutter-c3945',
    authDomain: 'auth-flutter-c3945.firebaseapp.com',
    storageBucket: 'auth-flutter-c3945.appspot.com',
    measurementId: 'G-RN52DKETTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpGTPhxemozRwxVuduMQqbF3JR4pwAYqI',
    appId: '1:649578057922:android:ebaeaa7a3ff6d230c32b5b',
    messagingSenderId: '649578057922',
    projectId: 'auth-flutter-c3945',
    storageBucket: 'auth-flutter-c3945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiwXK5T9ZWjGlBuMrdbX4tgX6AfvPP-N4',
    appId: '1:649578057922:ios:04a4af4b355f0e43c32b5b',
    messagingSenderId: '649578057922',
    projectId: 'auth-flutter-c3945',
    storageBucket: 'auth-flutter-c3945.appspot.com',
    iosBundleId: 'com.example.nopelGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiwXK5T9ZWjGlBuMrdbX4tgX6AfvPP-N4',
    appId: '1:649578057922:ios:f9a91c9c942f2ed9c32b5b',
    messagingSenderId: '649578057922',
    projectId: 'auth-flutter-c3945',
    storageBucket: 'auth-flutter-c3945.appspot.com',
    iosBundleId: 'com.example.nopelGet.RunnerTests',
  );
}
